name: 'Setup and build'
description: 'Setup and build Session Desktop'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.15.0
        cache: 'pnpm'
        cache-dependency-path: |
          'packages/*/package.json'
          frontend/app/package-lock.json
          pnpm-lock.yaml
          package.json
          'patches/**'


    - uses: pnpm/action-setup@v3
      with:
        version: 9

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # - name: Cache Desktop node_modules
    #   id: cache-desktop-modules
    #   uses: actions/cache@v3
    #   if: runner.os != 'Windows'
    #   with:
    #     path: node_modules
    #     key: ${{ runner.os }}-${{ hashFiles('package.json', 'pnpm-lock.yaml', 'patches/**') }}

    # Not having this will break the windows build because the PATH won't be set by msbuild.
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      if: runner.os == 'Windows'

    - name: Setup node for windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        pnpm add -g node-gyp@latest

    - name: patch pnpm
      if: runner.os == 'Windows'

      run: |
        find .  C:/Users/runneradmin/setup-pnpm/node_modules/pnpm -type d && sed -i 's/\/usr\/bin\/env node/node/g' C:/Users/runneradmin/setup-pnpm/node_modules/pnpm/bin/pnpm.cjs
      shell: bash

    # - name: Install dependencies
    #   shell: bash
    #   if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
    #   run: pnpm install --frozen-lockfile

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate and concat files
      shell: bash
      run: |
        pnpm session build-everything
        pnpm session tsc # we don't type check with webpack (transpileOnly: true) for speed reasons, so we need to make sure the types are right
