# This script will run tests anytime a pull request is added
name: Session Test

on:
  pull_request:
    branches:
      - clearnet
      - unstable
      - release/

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-12, ubuntu-20.04]
    env:
      SIGNAL_ENV: production
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Setup & Build
        uses: ./actions/setup_and_build

      - name: Lint Files
        # no need to lint files on all platforms. Just do it once on the quicker one
        if: runner.os == 'Linux'
        run: yarn lint-full

      - name: Enforce yarn.lock has no duplicates
        uses: ./actions/deduplicate_fail

      - name: Unit Test
        run: yarn test
